/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.DriverManager;
import java.time.temporal.Temporal;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author sueda
 */
public class Uygulama_Staj extends javax.swing.JFrame {

    /**
     * Creates new form Uygulama_Staj
     */
    int [] dizi;
    int obebSayiAdet;
      JPanel [] paneller = new JPanel[5];
    public Uygulama_Staj() {
        initComponents();
        paneller[0] = jPanel2;
        paneller[1] = jPanel3;
        paneller[2] = jPanel4;
        paneller[3] = jPanel5;
        paneller[4] = jPanel6;
        
        for (JPanel pnl : paneller) {
           pnl.setVisible(false);
       }
        /*nObebEkle.setVisible(false);
        nObebHesapla.setVisible(false);
        nObebSayi.setVisible(false);
        nobebCikti1.setVisible(false);
        nokekCikti1.setVisible(false);
        obebDizi.setVisible(false);
        label10.setVisible(false);
        label11.setVisible(false);
        label9.setVisible(false);
        label6.setVisible(false);*/
        
        
    }
public void panelGoster(JPanel jp){
       
       for (JPanel pnl : paneller) {
           pnl.setVisible(false);
       }
       jp.setVisible(true);
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        asalCarpan = new javax.swing.JButton();
        ikiSayiobeb = new javax.swing.JButton();
        nSayiObeb = new javax.swing.JButton();
        fibonacci = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        asalSayiGiris = new java.awt.TextField();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        asalCarpanHesapla = new javax.swing.JButton();
        asalCarpanCikti = new java.awt.TextArea();
        label9 = new java.awt.Label();
        jPanel3 = new javax.swing.JPanel();
        obebSayi1 = new javax.swing.JTextField();
        obebSayi2 = new javax.swing.JTextField();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        button1 = new java.awt.Button();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        obebCikti = new javax.swing.JTextField();
        okekCikti = new javax.swing.JTextField();
        label13 = new java.awt.Label();
        jPanel4 = new javax.swing.JPanel();
        label12 = new java.awt.Label();
        nObebSayiAdet = new java.awt.TextField();
        nObebTamam = new javax.swing.JButton();
        label14 = new java.awt.Label();
        jPanel5 = new javax.swing.JPanel();
        label3 = new java.awt.Label();
        jButton1 = new javax.swing.JButton();
        fibonaccideger = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        label6 = new java.awt.Label();
        nObebSayiGir = new java.awt.TextField();
        nObebEkle = new javax.swing.JButton();
        label10 = new java.awt.Label();
        label11 = new java.awt.Label();
        nObebHesapla = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        nObebSayilar = new javax.swing.JTextArea();
        nObebCikti = new javax.swing.JTextField();
        nOkekCikti = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(213, 248, 248));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        asalCarpan.setBackground(new java.awt.Color(250, 250, 129));
        asalCarpan.setText("1- Asal Çarpan");
        asalCarpan.setActionCommand("asalcarpan");
        asalCarpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asalCarpanActionPerformed(evt);
            }
        });

        ikiSayiobeb.setBackground(new java.awt.Color(250, 250, 129));
        ikiSayiobeb.setText("2- OBEB-OKEK");
        ikiSayiobeb.setActionCommand("asalcarpan");
        ikiSayiobeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ikiSayiobebActionPerformed(evt);
            }
        });

        nSayiObeb.setBackground(new java.awt.Color(250, 250, 129));
        nSayiObeb.setText("3- n sayı OBEB-OKEK");
        nSayiObeb.setActionCommand("asalcarpan");
        nSayiObeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nSayiObebActionPerformed(evt);
            }
        });

        fibonacci.setBackground(new java.awt.Color(250, 250, 129));
        fibonacci.setText("4- Fibonacci");
        fibonacci.setActionCommand("asalcarpan");
        fibonacci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fibonacciActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(asalCarpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ikiSayiobeb, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
            .addComponent(nSayiObeb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
            .addComponent(fibonacci, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(asalCarpan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(ikiSayiobeb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(nSayiObeb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fibonacci, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(566, 370));

        asalSayiGiris.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                asalSayiGirisKeyTyped(evt);
            }
        });

        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Bir sayı giriniz:");

        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("Girilen sayının asal çarpanları: ");

        asalCarpanHesapla.setBackground(new java.awt.Color(255, 255, 255));
        asalCarpanHesapla.setText("Hesapla");
        asalCarpanHesapla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asalCarpanHesaplaActionPerformed(evt);
            }
        });

        asalCarpanCikti.setEditable(false);

        label9.setBackground(new java.awt.Color(204, 204, 204));
        label9.setText("Girilen sayıyı asal çarpanlarına ayıran uygulama");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(asalCarpanCikti, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(asalCarpanHesapla))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(asalSayiGiris, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asalSayiGiris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(asalCarpanHesapla)
                .addGap(53, 53, 53)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(asalCarpanCikti, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setPreferredSize(new java.awt.Dimension(566, 370));

        obebSayi1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                obebSayi1KeyTyped(evt);
            }
        });

        obebSayi2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                obebSayi2KeyTyped(evt);
            }
        });

        label4.setForeground(new java.awt.Color(255, 255, 255));
        label4.setText("İkinci sayıyı giriniz: ");

        label5.setForeground(new java.awt.Color(255, 255, 255));
        label5.setText("Birinci sayıyı giriniz: ");

        button1.setLabel("Hesapla");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        label7.setForeground(new java.awt.Color(255, 255, 255));
        label7.setText("OBEB değeri:");

        label8.setForeground(new java.awt.Color(255, 255, 255));
        label8.setText("OKEK değeri:");

        obebCikti.setEditable(false);
        obebCikti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obebCiktiActionPerformed(evt);
            }
        });

        okekCikti.setEditable(false);

        label13.setBackground(new java.awt.Color(204, 204, 204));
        label13.setText("Girilen iki sayının OBEB ve OKEK ini bulan uygulama");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(okekCikti, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(obebCikti))))
                .addGap(118, 118, 118))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(obebSayi1)
                            .addComponent(obebSayi2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(obebSayi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(obebSayi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(obebCikti)
                    .addComponent(label7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(okekCikti)
                    .addComponent(label8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55))
        );

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setPreferredSize(new java.awt.Dimension(566, 370));

        label12.setForeground(new java.awt.Color(255, 255, 255));
        label12.setText("Hesaplanacak sayı adedini girin:");

        nObebSayiAdet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nObebSayiAdetKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nObebSayiAdetKeyTyped(evt);
            }
        });

        nObebTamam.setText("Tamam");
        nObebTamam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nObebTamamActionPerformed(evt);
            }
        });

        label14.setBackground(new java.awt.Color(204, 204, 204));
        label14.setText("Girilen n sayının OBEB ve OKEK ini nesneye yönelimli programlama yöntemi ile bulunması");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nObebSayiAdet, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(nObebTamam)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 57, Short.MAX_VALUE)
                .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nObebSayiAdet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(nObebTamam)
                .addGap(0, 242, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setPreferredSize(new java.awt.Dimension(566, 370));

        label3.setBackground(new java.awt.Color(204, 204, 204));
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setText("Fibonacci serisinin 10000.değerinin son 6 hanesi:");

        jButton1.setText("Hesapla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        fibonaccideger.setEditable(false);
        fibonaccideger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fibonaccidegerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fibonaccideger, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(228, 228, 228))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jButton1)))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(fibonaccideger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addContainerGap(248, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setPreferredSize(new java.awt.Dimension(566, 370));

        label6.setForeground(new java.awt.Color(255, 255, 255));
        label6.setText("Sayıları giriniz");

        nObebSayiGir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nObebSayiGirKeyTyped(evt);
            }
        });

        nObebEkle.setText("Ekle");
        nObebEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nObebEkleActionPerformed(evt);
            }
        });

        label10.setForeground(new java.awt.Color(255, 255, 255));
        label10.setText("OBEB Değeri:");

        label11.setForeground(new java.awt.Color(255, 255, 255));
        label11.setText("OKEK Değeri:");

        nObebHesapla.setText("Hesapla");
        nObebHesapla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nObebHesaplaActionPerformed(evt);
            }
        });

        nObebSayilar.setEditable(false);
        nObebSayilar.setColumns(20);
        nObebSayilar.setRows(5);
        jScrollPane1.setViewportView(nObebSayilar);

        nObebCikti.setEditable(false);

        nOkekCikti.setEditable(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nObebSayiGir, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addComponent(nObebEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nObebHesapla)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(label10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(label11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nObebCikti, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nOkekCikti, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(223, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nObebSayiGir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nObebEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nObebHesapla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nObebCikti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 73, Short.MAX_VALUE)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nOkekCikti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(114, 114, 114))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 172, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 172, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 171, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 172, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void asalCarpanHesaplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asalCarpanHesaplaActionPerformed
        int sayi;
        String ciktilar = "";
        sayi=Integer.valueOf(asalSayiGiris.getText());
        if(sayi<=1 || asalSayiGiris.getText()==null){
            JOptionPane.showMessageDialog(null, "Lütfen 1'den farklı pozitif bir tam sayı giriniz");
        }
        else{
            int i=2;
            int temp=sayi;
            while(i<=sayi){
                
                if(temp%i==0){
                    
                    ciktilar = ciktilar+i+"\n";
                    temp= temp/i;
                }
                else{
                    i++;
                }
            }
           
            asalCarpanCikti.setText(ciktilar);
            
        }
    }//GEN-LAST:event_asalCarpanHesaplaActionPerformed

    private void ikiSayiobebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ikiSayiobebActionPerformed
        panelGoster(jPanel3);
    }//GEN-LAST:event_ikiSayiobebActionPerformed

    private void asalCarpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asalCarpanActionPerformed
        panelGoster(jPanel2);
    }//GEN-LAST:event_asalCarpanActionPerformed

    private void nSayiObebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nSayiObebActionPerformed
         panelGoster(jPanel4);
    }//GEN-LAST:event_nSayiObebActionPerformed

    private void fibonacciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fibonacciActionPerformed
         panelGoster(jPanel5);
    }//GEN-LAST:event_fibonacciActionPerformed

    private void asalSayiGirisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_asalSayiGirisKeyTyped
    char c = evt.getKeyChar();
    if(!Character.isDigit(c)){
        evt.consume();
    }
    }//GEN-LAST:event_asalSayiGirisKeyTyped

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
      int sayi1, sayi2, i, obeb=1, okek=0;
      
      sayi1= Integer.valueOf(obebSayi1.getText());
      sayi2= Integer.valueOf(obebSayi2.getText());
      if(sayi1==0||sayi2==0 || obebSayi2.getText()==null || obebSayi1.getText()==null){
          JOptionPane.showMessageDialog(null, "Giridiğiniz sayılar pozitif tam sayı olmalı.");
      }
      else{
          
      
      for(i=1;i<=sayi1 && i<=sayi2; i++){
          if(sayi1%i==0 && sayi2%i==0){
              obeb = i;
              okek = (sayi1*sayi2)/obeb;
          }
      }
        
       
      obebCikti.setText(String.valueOf(obeb));
      okekCikti.setText(String.valueOf(okek));
      }
    }//GEN-LAST:event_button1ActionPerformed

    private void obebCiktiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obebCiktiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obebCiktiActionPerformed

    private void obebSayi1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_obebSayi1KeyTyped
      char c = evt.getKeyChar();
    if(!Character.isDigit(c)){
        evt.consume();
    }
    }//GEN-LAST:event_obebSayi1KeyTyped

    private void obebSayi2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_obebSayi2KeyTyped
     char c = evt.getKeyChar();
    if(!Character.isDigit(c) ){
        evt.consume();
    }
    }//GEN-LAST:event_obebSayi2KeyTyped
/*
    private void nObebTamamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nObebTamamActionPerformed
        
    }//GEN-LAST:event_nObebTamamActionPerformed
*/
    private void nObebEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nObebEkleActionPerformed
        
        
         if (obebSayiAdet<=0){
            JOptionPane.showMessageDialog(null, "Tüm sayıları girdiniz lütfen hesapla butonuna tıklayınız.");
        }
            dizi[obebSayiAdet-1]=Integer.valueOf(nObebSayiGir.getText());
            obebSayiAdet--;
            nObebSayilar.setText(nObebSayilar.getText()+nObebSayiGir.getText()+"\n");
        
       
       
        
    }//GEN-LAST:event_nObebEkleActionPerformed

    private void nObebHesaplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nObebHesaplaActionPerformed
        nSayiObeb o1 = new nSayiObeb();
        nSayiOkek o2 = new nSayiOkek();
        int obeb, okek;
        obeb = o1.nSayiObeb(dizi);
        okek = o2.nSayiOkek(dizi);
        nObebCikti.setText(String.valueOf(obeb));
        nOkekCikti.setText(String.valueOf(okek));
    }//GEN-LAST:event_nObebHesaplaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Fibonacci hesapla = new Fibonacci();
        int deger;
        deger=hesapla.fibonacciHesapla();
        fibonaccideger.setText(String.valueOf(deger));
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fibonaccidegerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fibonaccidegerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fibonaccidegerActionPerformed

    private void nObebSayiAdetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nObebSayiAdetKeyPressed
   
    
    }//GEN-LAST:event_nObebSayiAdetKeyPressed

    private void nObebSayiGirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nObebSayiGirKeyTyped
        char c = evt.getKeyChar();
    if(!Character.isDigit(c) ){
        evt.consume();
    }
    }//GEN-LAST:event_nObebSayiGirKeyTyped

    private void nObebSayiAdetKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nObebSayiAdetKeyTyped
      char c = evt.getKeyChar();
    if(!Character.isDigit(c) ){
        evt.consume();
    }
    }//GEN-LAST:event_nObebSayiAdetKeyTyped

    public void nObebTamamActionPerformed(java.awt.event.ActionEvent evt){
    obebSayiAdet = Integer.valueOf(nObebSayiAdet.getText());
    if(String.valueOf(obebSayiAdet)==null||obebSayiAdet<=1){
         JOptionPane.showMessageDialog(null, "Lütfen OBEB ve OKEK değerlerini hesaplamak istediğiniz sayı adedini giriniz.");
    }
    else{
        dizi = new int [obebSayiAdet]; 
        panelGoster(jPanel6);
        
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Uygulama_Staj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Uygulama_Staj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Uygulama_Staj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Uygulama_Staj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Uygulama_Staj().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton asalCarpan;
    private java.awt.TextArea asalCarpanCikti;
    private javax.swing.JButton asalCarpanHesapla;
    private java.awt.TextField asalSayiGiris;
    private java.awt.Button button1;
    private javax.swing.JButton fibonacci;
    private javax.swing.JTextField fibonaccideger;
    private javax.swing.JButton ikiSayiobeb;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private javax.swing.JTextField nObebCikti;
    private javax.swing.JButton nObebEkle;
    private javax.swing.JButton nObebHesapla;
    private java.awt.TextField nObebSayiAdet;
    private java.awt.TextField nObebSayiGir;
    private javax.swing.JTextArea nObebSayilar;
    private javax.swing.JButton nObebTamam;
    private javax.swing.JTextField nOkekCikti;
    private javax.swing.JButton nSayiObeb;
    private javax.swing.JTextField obebCikti;
    private javax.swing.JTextField obebSayi1;
    private javax.swing.JTextField obebSayi2;
    private javax.swing.JTextField okekCikti;
    // End of variables declaration//GEN-END:variables
}
